import gzip
import io
from pathlib import Path

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
SOURCE_CPP = PROJECT_DIR / "src" / "web" / "WebTemplatesDashboardAp.cpp"
OUT_INC = PROJECT_DIR / "src" / "web" / "generated" / "WebTemplatesDashboardApGzip.inc"

START_MARKER = 'const char kDashboardPageTemplateAp[] PROGMEM = R"HTML_DASH_AP(\n'
END_MARKER = ')HTML_DASH_AP";'
# NOTE: these markers must stay in sync with WebTemplatesDashboardAp.cpp.


def extract_dashboard_html(source_path: Path) -> str:
    text = source_path.read_text(encoding="utf-8")
    start = text.find(START_MARKER)
    if start < 0:
        raise RuntimeError(
            f"Dashboard template start marker not found in {source_path}"
        )
    start += len(START_MARKER)

    end = text.find(END_MARKER, start)
    if end < 0:
        raise RuntimeError(
            f"Dashboard template end marker not found in {source_path}"
        )

    return text[start:end]


def gzip_bytes(data: bytes) -> bytes:
    buffer = io.BytesIO()
    with gzip.GzipFile(
        filename="dashboard.html", mode="wb", fileobj=buffer, compresslevel=9, mtime=0
    ) as gz:
        gz.write(data)
    return buffer.getvalue()


def render_inc(payload: bytes) -> str:
    lines = [
        "// Auto-generated by scripts/generate_dashboard_gzip.py. Do not edit manually.",
        "",
        "const uint8_t kDashboardPageTemplateApGzip[] PROGMEM = {",
    ]
    bytes_per_line = 12
    for index in range(0, len(payload), bytes_per_line):
        chunk = payload[index : index + bytes_per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.extend(
        [
            "};",
            f"const size_t kDashboardPageTemplateApGzipSize = {len(payload)};",
            "",
        ]
    )
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> None:
    html = extract_dashboard_html(SOURCE_CPP)
    html_bytes = html.encode("utf-8")
    payload = gzip_bytes(html_bytes)
    inc_content = render_inc(payload)
    changed = write_if_changed(OUT_INC, inc_content)

    status = "updated" if changed else "up-to-date"
    print(
        f"[dashboard-gzip] {status}: source={len(html_bytes)} bytes, gzip={len(payload)} bytes"
    )


main()
